# Generated by Django 4.1.2 on 2022-10-19 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donermodel',
            old_name='bloodgroupchoices',
            new_name='bloodgroup',
        ),
    ]
